sudo: required

services:
    - docker

before_install:
    - docker build -t layziebone/client-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true layziebone/client-test npm test -- --coverage

after_success:
    - docker build layziebone/multi-client ./client
    - docker build layziebone/multi-nginx ./nginx
    - docker build layziebone/multi-server ./server
    - docker build layziebone/multi-worker ./worker
#docker login to move build to docker hub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin "$DOCKER_PASSWORD"
#push files to docker hub
    - docker push layziebone/multi-client
    - docker push layziebone/multi-nginx
    - docker push layziebone/multi-server
    - docker push layziebone/multi-worker